package combiz.domain.doclib;



/**
 * Docauth generated by MyEclipse - Hibernate Tools
 */

public class Docauth  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String docnum;
     private String grpname;
     private String docread;
     private String docedit;
     private String memo;


    // Constructors

    /** default constructor */
    public Docauth() {
    }

	/** minimal constructor */
    public Docauth(String docnum, String grpname, String docread, String docedit) {
        this.docnum = docnum;
        this.grpname = grpname;
        this.docread = docread;
        this.docedit = docedit;
    }
    
    /** full constructor */
    public Docauth(String docnum, String grpname, String docread, String docedit, String memo) {
        this.docnum = docnum;
        this.grpname = grpname;
        this.docread = docread;
        this.docedit = docedit;
        this.memo = memo;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getDocnum() {
        return this.docnum;
    }
    
    public void setDocnum(String docnum) {
        this.docnum = docnum;
    }

    public String getGrpname() {
        return this.grpname;
    }
    
    public void setGrpname(String grpname) {
        this.grpname = grpname;
    }

    public String getDocread() {
        return this.docread;
    }
    
    public void setDocread(String docread) {
        this.docread = docread;
    }

    public String getDocedit() {
        return this.docedit;
    }
    
    public void setDocedit(String docedit) {
        this.docedit = docedit;
    }

    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }
   








}