package combiz.domain.doclib;



/**
 * Doclibance generated by MyEclipse - Hibernate Tools
 */

public class Doclibance  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String libnum;
     private String ancestor;


    // Constructors

    /** default constructor */
    public Doclibance() {
    }

    
    /** full constructor */
    public Doclibance(String libnum, String ancestor) {
        this.libnum = libnum;
        this.ancestor = ancestor;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getLibnum() {
        return this.libnum;
    }
    
    public void setLibnum(String libnum) {
        this.libnum = libnum;
    }

    public String getAncestor() {
        return this.ancestor;
    }
    
    public void setAncestor(String ancestor) {
        this.ancestor = ancestor;
    }
   








}