package combiz.domain.ibs;



/**
 * Ibsidgen generated by MyEclipse - Hibernate Tools
 */

public class Ibsidgen  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String tablename;
     private Long seed;
     private Long idvalue;
     private String memo;


    // Constructors

    /** default constructor */
    public Ibsidgen() {
    }

	/** minimal constructor */
    public Ibsidgen(Long id, String tablename, Long seed, Long idvalue) {
        this.id = id;
        this.tablename = tablename;
        this.seed = seed;
        this.idvalue = idvalue;
    }
    
    /** full constructor */
    public Ibsidgen(Long id, String tablename, Long seed, Long idvalue, String memo) {
        this.id = id;
        this.tablename = tablename;
        this.seed = seed;
        this.idvalue = idvalue;
        this.memo = memo;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getTablename() {
        return this.tablename;
    }
    
    public void setTablename(String tablename) {
        this.tablename = tablename;
    }

    public Long getSeed() {
        return this.seed;
    }
    
    public void setSeed(Long seed) {
        this.seed = seed;
    }

    public Long getIdvalue() {
        return this.idvalue;
    }
    
    public void setIdvalue(Long idvalue) {
        this.idvalue = idvalue;
    }

    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }
   








}