package combiz.domain.failure;



/**
 * Failurecode generated by MyEclipse - Hibernate Tools
 */

public class Failurecode  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String failurecode;
     private String description;
     private String classid;


    // Constructors

    /** default constructor */
    public Failurecode() {
    }

	/** minimal constructor */
    public Failurecode(String failurecode) {
        this.failurecode = failurecode;
    }
    
    /** full constructor */
    public Failurecode(String failurecode, String description, String classid) {
        this.failurecode = failurecode;
        this.description = description;
        this.classid = classid;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getFailurecode() {
        return this.failurecode;
    }
    
    public void setFailurecode(String failurecode) {
        this.failurecode = failurecode;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getClassid() {
        return this.classid;
    }
    
    public void setClassid(String classid) {
        this.classid = classid;
    }
   








}