package combiz.domain.failure;



/**
 * Failureproblem generated by MyEclipse - Hibernate Tools
 */

public class Failureproblem  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String failurecode;
     private String failureproblem;
     private String description;
     private String rank;


    // Constructors

    /** default constructor */
    public Failureproblem() {
    }

	/** minimal constructor */
    public Failureproblem(String failurecode, String failureproblem) {
        this.failurecode = failurecode;
        this.failureproblem = failureproblem;
    }
    
    /** full constructor */
    public Failureproblem(String failurecode, String failureproblem, String description, String rank) {
        this.failurecode = failurecode;
        this.failureproblem = failureproblem;
        this.description = description;
        this.rank = rank;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getFailurecode() {
        return this.failurecode;
    }
    
    public void setFailurecode(String failurecode) {
        this.failurecode = failurecode;
    }

    public String getFailureproblem() {
        return this.failureproblem;
    }
    
    public void setFailureproblem(String failureproblem) {
        this.failureproblem = failureproblem;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getRank() {
        return this.rank;
    }
    
    public void setRank(String rank) {
        this.rank = rank;
    }
   








}