package combiz.domain.failure;



/**
 * Failuredeal generated by MyEclipse - Hibernate Tools
 */

public class Failuredeal  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String failurecause;
     private String failuredeal;
     private String description;


    // Constructors

    /** default constructor */
    public Failuredeal() {
    }

	/** minimal constructor */
    public Failuredeal(String failurecause, String failuredeal) {
        this.failurecause = failurecause;
        this.failuredeal = failuredeal;
    }
    
    /** full constructor */
    public Failuredeal(String failurecause, String failuredeal, String description) {
        this.failurecause = failurecause;
        this.failuredeal = failuredeal;
        this.description = description;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getFailurecause() {
        return this.failurecause;
    }
    
    public void setFailurecause(String failurecause) {
        this.failurecause = failurecause;
    }

    public String getFailuredeal() {
        return this.failuredeal;
    }
    
    public void setFailuredeal(String failuredeal) {
        this.failuredeal = failuredeal;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
   








}