package combiz.domain.workorder;



/**
 * Wohazardprec generated by MyEclipse - Hibernate Tools
 */

public class Wohazardprec  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String wonum;
     private String hazardid;
     private String hazardprec;
     private String description;


    // Constructors

    /** default constructor */
    public Wohazardprec() {
    }

	/** minimal constructor */
    public Wohazardprec(String wonum, String hazardid, String hazardprec) {
        this.wonum = wonum;
        this.hazardid = hazardid;
        this.hazardprec = hazardprec;
    }
    
    /** full constructor */
    public Wohazardprec(String wonum, String hazardid, String hazardprec, String description) {
        this.wonum = wonum;
        this.hazardid = hazardid;
        this.hazardprec = hazardprec;
        this.description = description;
    }

   
    // Property accessors

    public String getWonum() {
        return this.wonum;
    }
    
    public void setWonum(String wonum) {
        this.wonum = wonum;
    }

    public String getHazardid() {
        return this.hazardid;
    }
    
    public void setHazardid(String hazardid) {
        this.hazardid = hazardid;
    }

    public String getHazardprec() {
        return this.hazardprec;
    }
    
    public void setHazardprec(String hazardprec) {
        this.hazardprec = hazardprec;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

	/**
	 * @return id
	 */
	public Long getId()
	{
		return id;
	}

	/**
	 * @param id ÒªÉèÖÃµÄ id
	 */
	public void setId(Long id)
	{
		this.id = id;
	}
   








}