package combiz.domain.workorder;



/**
 * Wohazard generated by MyEclipse - Hibernate Tools
 */

public class Wohazard  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String wonum;
     private String hazardid;
     private String description;
     private String hazprec;
     private String hazmat;
     private String haztagout;
     private String hazardtype;
     private String msdsnum;
     private Long health;


    // Constructors

    /** default constructor */
    public Wohazard() {
    }

	/** minimal constructor */
    public Wohazard(String wonum, String hazardid, String hazprec, String hazmat, String haztagout) {
        this.wonum = wonum;
        this.hazardid = hazardid;
        this.hazprec = hazprec;
        this.hazmat = hazmat;
        this.haztagout = haztagout;
    }
    
    /** full constructor */
    public Wohazard(String wonum, String hazardid, String description, String hazprec, String hazmat, String haztagout, String hazardtype, String msdsnum, Long health) {
        this.wonum = wonum;
        this.hazardid = hazardid;
        this.description = description;
        this.hazprec = hazprec;
        this.hazmat = hazmat;
        this.haztagout = haztagout;
        this.hazardtype = hazardtype;
        this.msdsnum = msdsnum;
        this.health = health;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getWonum() {
        return this.wonum;
    }
    
    public void setWonum(String wonum) {
        this.wonum = wonum;
    }

    public String getHazardid() {
        return this.hazardid;
    }
    
    public void setHazardid(String hazardid) {
        this.hazardid = hazardid;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getHazprec() {
        return this.hazprec;
    }
    
    public void setHazprec(String hazprec) {
        this.hazprec = hazprec;
    }

    public String getHazmat() {
        return this.hazmat;
    }
    
    public void setHazmat(String hazmat) {
        this.hazmat = hazmat;
    }

    public String getHaztagout() {
        return this.haztagout;
    }
    
    public void setHaztagout(String haztagout) {
        this.haztagout = haztagout;
    }

    public String getHazardtype() {
        return this.hazardtype;
    }
    
    public void setHazardtype(String hazardtype) {
        this.hazardtype = hazardtype;
    }

    public String getMsdsnum() {
        return this.msdsnum;
    }
    
    public void setMsdsnum(String msdsnum) {
        this.msdsnum = msdsnum;
    }

    public Long getHealth() {
        return this.health;
    }
    
    public void setHealth(Long health) {
        this.health = health;
    }
   








}