package combiz.domain.workorder;

import java.util.Date;


/**
 * Wostatus generated by MyEclipse - Hibernate Tools
 */

public class Wostatus  implements java.io.Serializable {


    // Fields    

     private String id;
     private String wonum;
     private String status;
     private Date changedate;
     private String changeby;
     private String remark;


    // Constructors

    /** default constructor */
    public Wostatus() {
    }

	/** minimal constructor */
    public Wostatus(String wonum, String status, Date changedate, String changeby) {
        this.wonum = wonum;
        this.status = status;
        this.changedate = changedate;
        this.changeby = changeby;
    }
    
    /** full constructor */
    public Wostatus(String wonum, String status, Date changedate, String changeby, String remark) {
        this.wonum = wonum;
        this.status = status;
        this.changedate = changedate;
        this.changeby = changeby;
        this.remark = remark;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getWonum() {
        return this.wonum;
    }
    
    public void setWonum(String wonum) {
        this.wonum = wonum;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public Date getChangedate() {
        return this.changedate;
    }
    
    public void setChangedate(Date changedate) {
        this.changedate = changedate;
    }

    public String getChangeby() {
        return this.changeby;
    }
    
    public void setChangeby(String changeby) {
        this.changeby = changeby;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
   








}