package combiz.domain.po;



/**
 * Conversion generated by MyEclipse - Hibernate Tools
 */

public class Conversion  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String orderunit;
     private String issueunit;
     private Double conversion;
     private String itemnum;


    // Constructors

    /** default constructor */
    public Conversion() {
    }

	/** minimal constructor */
    public Conversion(String orderunit, String issueunit, Double conversion) {
        this.orderunit = orderunit;
        this.issueunit = issueunit;
        this.conversion = conversion;
    }
    
    /** full constructor */
    public Conversion(String orderunit, String issueunit, Double conversion, String itemnum) {
        this.orderunit = orderunit;
        this.issueunit = issueunit;
        this.conversion = conversion;
        this.itemnum = itemnum;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getOrderunit() {
        return this.orderunit;
    }
    
    public void setOrderunit(String orderunit) {
        this.orderunit = orderunit;
    }

    public String getIssueunit() {
        return this.issueunit;
    }
    
    public void setIssueunit(String issueunit) {
        this.issueunit = issueunit;
    }

    public Double getConversion() {
        return this.conversion;
    }
    
    public void setConversion(Double conversion) {
        this.conversion = conversion;
    }

    public String getItemnum() {
        return this.itemnum;
    }
    
    public void setItemnum(String itemnum) {
        this.itemnum = itemnum;
    }
   








}