package combiz.domain.po;



/**
 * Orderunit generated by MyEclipse - Hibernate Tools
 */

public class Orderunit  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String orderunit;
     private String description;


    // Constructors

    /** default constructor */
    public Orderunit() {
    }

    
    /** full constructor */
    public Orderunit(String orderunit, String description) {
        this.orderunit = orderunit;
        this.description = description;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getOrderunit() {
        return this.orderunit;
    }
    
    public void setOrderunit(String orderunit) {
        this.orderunit = orderunit;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
   








}