package combiz.domain.stdplan;



/**
 * Isolockout generated by MyEclipse - Hibernate Tools
 */

public class Isolockout  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String isotagid;
     private String isolockid;
     private String description;
     private String location;
     private String eqnum;
     private String eqdescriptioin;
     private String state;
     private Long aplyseq;


    // Constructors

    /** default constructor */
    public Isolockout() {
    }

	/** minimal constructor */
    public Isolockout(String isotagid, String isolockid, String description, Long aplyseq) {
        this.isotagid = isotagid;
        this.isolockid = isolockid;
        this.description = description;
        this.aplyseq = aplyseq;
    }
    
    /** full constructor */
    public Isolockout(String isotagid, String isolockid, String description, String location, String eqnum, String eqdescriptioin, String state, Long aplyseq) {
        this.isotagid = isotagid;
        this.isolockid = isolockid;
        this.description = description;
        this.location = location;
        this.eqnum = eqnum;
        this.eqdescriptioin = eqdescriptioin;
        this.state = state;
        this.aplyseq = aplyseq;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getIsotagid() {
        return this.isotagid;
    }
    
    public void setIsotagid(String isotagid) {
        this.isotagid = isotagid;
    }

    public String getIsolockid() {
        return this.isolockid;
    }
    
    public void setIsolockid(String isolockid) {
        this.isolockid = isolockid;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    public String getEqnum() {
        return this.eqnum;
    }
    
    public void setEqnum(String eqnum) {
        this.eqnum = eqnum;
    }

    public String getEqdescriptioin() {
        return this.eqdescriptioin;
    }
    
    public void setEqdescriptioin(String eqdescriptioin) {
        this.eqdescriptioin = eqdescriptioin;
    }

    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    public Long getAplyseq() {
        return this.aplyseq;
    }
    
    public void setAplyseq(Long aplyseq) {
        this.aplyseq = aplyseq;
    }
   








}