package combiz.domain.stdplan;



/**
 * Joblabor generated by MyEclipse - Hibernate Tools
 */

public class Joblabor  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String jpnum;
     private String tasknum;
     private String labornum;
     private Long qty;
     private Float laborhrs;
     private Double rate;
     private String vendor;


    // Constructors

    /** default constructor */
    public Joblabor() {
    }

	/** minimal constructor */
    public Joblabor(String jpnum, String labornum, Long qty, Float laborhrs, Double rate) {
        this.jpnum = jpnum;
        this.labornum = labornum;
        this.qty = qty;
        this.laborhrs = laborhrs;
        this.rate = rate;
    }
    
    /** full constructor */
    public Joblabor(String jpnum, String tasknum, String labornum, Long qty, Float laborhrs, Double rate, String vendor) {
        this.jpnum = jpnum;
        this.tasknum = tasknum;
        this.labornum = labornum;
        this.qty = qty;
        this.laborhrs = laborhrs;
        this.rate = rate;
        this.vendor = vendor;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getJpnum() {
        return this.jpnum;
    }
    
    public void setJpnum(String jpnum) {
        this.jpnum = jpnum;
    }

    public String getTasknum() {
        return this.tasknum;
    }
    
    public void setTasknum(String tasknum) {
        this.tasknum = tasknum;
    }

    public String getLabornum() {
        return this.labornum;
    }
    
    public void setLabornum(String labornum) {
        this.labornum = labornum;
    }

    public Long getQty() {
        return this.qty;
    }
    
    public void setQty(Long qty) {
        this.qty = qty;
    }

    public Float getLaborhrs() {
        return this.laborhrs;
    }
    
    public void setLaborhrs(Float laborhrs) {
        this.laborhrs = laborhrs;
    }

    public Double getRate() {
        return this.rate;
    }
    
    public void setRate(Double rate) {
        this.rate = rate;
    }

    public String getVendor() {
        return this.vendor;
    }
    
    public void setVendor(String vendor) {
        this.vendor = vendor;
    }
   








}