<?xml version="1.0"?>
<!DOCTYPE hibernate-mapping PUBLIC "-//Hibernate/Hibernate Mapping DTD 3.0//EN"
"http://hibernate.sourceforge.net/hibernate-mapping-3.0.dtd">
<!-- 
    Mapping file autogenerated by MyEclipse - Hibernate Tools
-->
<hibernate-mapping>
    <class name="${classname}" table="${tablename}">
        <id name="id" type="java.lang.Long">
            <column name="ID" precision="22" scale="0" />
            <generator class="assigned" />
        </id>
        <#list props as prop>
        <property name="${prop.name}" type="${prop.type}">
            <column name="${prop.colname}" length="${prop.collen}" <#if prop.notnull?exists>not-null="${prop.notnull}"</#if>  <#if prop.unique?exists> unique="${prop.unique}" </#if>/>
        </property>
        </#list>
    </class>
</hibernate-mapping>
