package combiz.domain.equipment;



/**
 * Eqance generated by MyEclipse - Hibernate Tools
 */

public class Eqance  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String eqnum;
     private String ancestor;


    // Constructors

    /** default constructor */
    public Eqance() {
    }

    
    /** full constructor */
    public Eqance(String eqnum, String ancestor) {
        this.eqnum = eqnum;
        this.ancestor = ancestor;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getEqnum() {
        return this.eqnum;
    }
    
    public void setEqnum(String eqnum) {
        this.eqnum = eqnum;
    }

    public String getAncestor() {
        return this.ancestor;
    }
    
    public void setAncestor(String ancestor) {
        this.ancestor = ancestor;
    }
   








}