package combiz.domain.equipment;



/**
 * Eqhiery generated by MyEclipse - Hibernate Tools
 */

public class Eqhiery  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String eqnum;
     private String parent;
     private String children;
     private Long eqlevel;
     private String leveltext;
     private String location;


    // Constructors

    /** default constructor */
    public Eqhiery() {
    }

	/** minimal constructor */
    public Eqhiery(String eqnum, String children, Long eqlevel) {
        this.eqnum = eqnum;
        this.children = children;
        this.eqlevel = eqlevel;
    }
    
    /** full constructor */
    public Eqhiery(String eqnum, String parent, String children, Long eqlevel, String leveltext, String location) {
        this.eqnum = eqnum;
        this.parent = parent;
        this.children = children;
        this.eqlevel = eqlevel;
        this.leveltext = leveltext;
        this.location = location;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getEqnum() {
        return this.eqnum;
    }
    
    public void setEqnum(String eqnum) {
        this.eqnum = eqnum;
    }

    public String getParent() {
        return this.parent;
    }
    
    public void setParent(String parent) {
        this.parent = parent;
    }

    public String getChildren() {
        return this.children;
    }
    
    public void setChildren(String children) {
        this.children = children;
    }

    public Long getEqlevel() {
        return this.eqlevel;
    }
    
    public void setEqlevel(Long eqlevel) {
        this.eqlevel = eqlevel;
    }

    public String getLeveltext() {
        return this.leveltext;
    }
    
    public void setLeveltext(String leveltext) {
        this.leveltext = leveltext;
    }

    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
   








}