package combiz.domain.equipment;



/**
 * Eqrelation generated by MyEclipse - Hibernate Tools
 */

public class Eqrelation  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String eqnum;
     private String reltype;
     private String relequipment;


    // Constructors

    /** default constructor */
    public Eqrelation() {
    }

    
    /** full constructor */
    public Eqrelation(String eqnum, String reltype, String relequipment) {
        this.eqnum = eqnum;
        this.reltype = reltype;
        this.relequipment = relequipment;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getEqnum() {
        return this.eqnum;
    }
    
    public void setEqnum(String eqnum) {
        this.eqnum = eqnum;
    }

    public String getReltype() {
        return this.reltype;
    }
    
    public void setReltype(String reltype) {
        this.reltype = reltype;
    }

    public String getRelequipment() {
        return this.relequipment;
    }
    
    public void setRelequipment(String relequipment) {
        this.relequipment = relequipment;
    }
   








}