package combiz.domain.equipment;

import java.util.Date;


/**
 * Eqstatus generated by MyEclipse - Hibernate Tools
 */

public class Eqstatus  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String eqnum;
     private String isrunning;
     private String status;
     private Date statusdate;
     private Date changedate;
     private String changeby;
     private Float downtime;
     private String code;
     private String location;


    // Constructors

    /** default constructor */
    public Eqstatus() {
    }

	/** minimal constructor */
    public Eqstatus(String eqnum, String isrunning, String status, Date statusdate, Date changedate, String changeby, Float downtime) {
        this.eqnum = eqnum;
        this.isrunning = isrunning;
        this.status = status;
        this.statusdate = statusdate;
        this.changedate = changedate;
        this.changeby = changeby;
        this.downtime = downtime;
    }
    
    /** full constructor */
    public Eqstatus(String eqnum, String isrunning, String status, Date statusdate, Date changedate, String changeby, Float downtime, String code, String location) {
        this.eqnum = eqnum;
        this.isrunning = isrunning;
        this.status = status;
        this.statusdate = statusdate;
        this.changedate = changedate;
        this.changeby = changeby;
        this.downtime = downtime;
        this.code = code;
        this.location = location;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getEqnum() {
        return this.eqnum;
    }
    
    public void setEqnum(String eqnum) {
        this.eqnum = eqnum;
    }

    public String getIsrunning() {
        return this.isrunning;
    }
    
    public void setIsrunning(String isrunning) {
        this.isrunning = isrunning;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public Date getStatusdate() {
        return this.statusdate;
    }
    
    public void setStatusdate(Date statusdate) {
        this.statusdate = statusdate;
    }

    public Date getChangedate() {
        return this.changedate;
    }
    
    public void setChangedate(Date changedate) {
        this.changedate = changedate;
    }

    public String getChangeby() {
        return this.changeby;
    }
    
    public void setChangeby(String changeby) {
        this.changeby = changeby;
    }

    public Float getDowntime() {
        return this.downtime;
    }
    
    public void setDowntime(Float downtime) {
        this.downtime = downtime;
    }

    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
   








}