package combiz.domain.user;

import java.util.Date;


/**
 * Ibsusers generated by MyEclipse - Hibernate Tools
 */

public class Ibsusers  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String userid;
     private String labornum;
     private String loginid;
     private String password;
     private Long failedlogins;
     private String paswdexpiration;
     private Date pwexpiration;
     private String status;
     private String issysuser;
     private String defstoreroom;
     private String remark;


    // Constructors

    /** default constructor */
    public Ibsusers() {
    }

	/** minimal constructor */
    public Ibsusers(String userid, String labornum, String loginid, String password, String paswdexpiration, String status, String issysuser) {
        this.userid = userid;
        this.labornum = labornum;
        this.loginid = loginid;
        this.password = password;
        this.paswdexpiration = paswdexpiration;
        this.status = status;
        this.issysuser = issysuser;
    }
    
    /** full constructor */
    public Ibsusers(String userid, String labornum, String loginid, String password, Long failedlogins, String paswdexpiration, Date pwexpiration, String status, String issysuser, String defstoreroom, String remark) {
        this.userid = userid;
        this.labornum = labornum;
        this.loginid = loginid;
        this.password = password;
        this.failedlogins = failedlogins;
        this.paswdexpiration = paswdexpiration;
        this.pwexpiration = pwexpiration;
        this.status = status;
        this.issysuser = issysuser;
        this.defstoreroom = defstoreroom;
        this.remark = remark;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getLabornum() {
        return this.labornum;
    }
    
    public void setLabornum(String labornum) {
        this.labornum = labornum;
    }

    public String getLoginid() {
        return this.loginid;
    }
    
    public void setLoginid(String loginid) {
        this.loginid = loginid;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public Long getFailedlogins() {
        return this.failedlogins;
    }
    
    public void setFailedlogins(Long failedlogins) {
        this.failedlogins = failedlogins;
    }

    public String getPaswdexpiration() {
        return this.paswdexpiration;
    }
    
    public void setPaswdexpiration(String paswdexpiration) {
        this.paswdexpiration = paswdexpiration;
    }

    public Date getPwexpiration() {
        return this.pwexpiration;
    }
    
    public void setPwexpiration(Date pwexpiration) {
        this.pwexpiration = pwexpiration;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public String getIssysuser() {
        return this.issysuser;
    }
    
    public void setIssysuser(String issysuser) {
        this.issysuser = issysuser;
    }

    public String getDefstoreroom() {
        return this.defstoreroom;
    }
    
    public void setDefstoreroom(String defstoreroom) {
        this.defstoreroom = defstoreroom;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
   








}