package combiz.domain.cal;

import java.util.Date;


/**
 * Calendar generated by MyEclipse - Hibernate Tools
 */

public class Calendar  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String calnum;
     private String description;
     private Date startdate;
     private Date enddate;


    // Constructors

    /** default constructor */
    public Calendar() {
    }

	/** minimal constructor */
    public Calendar(String calnum, Date startdate, Date enddate) {
        this.calnum = calnum;
        this.startdate = startdate;
        this.enddate = enddate;
    }
    
    /** full constructor */
    public Calendar(String calnum, String description, Date startdate, Date enddate) {
        this.calnum = calnum;
        this.description = description;
        this.startdate = startdate;
        this.enddate = enddate;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getCalnum() {
        return this.calnum;
    }
    
    public void setCalnum(String calnum) {
        this.calnum = calnum;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }
   








}