package combiz.domain.cal;



/**
 * Calshift generated by MyEclipse - Hibernate Tools
 */

public class Calshift  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String shiftnum;
     private String description;
     private String startday;
     private Long daymold;


    // Constructors

	/** default constructor */
    public Calshift() {
    }

	/** minimal constructor */
    public Calshift(String shiftnum, String startday) {
        this.shiftnum = shiftnum;
        this.startday = startday;
    }
    
    /** full constructor */
    public Calshift(String shiftnum, String description, String startday) {
        this.shiftnum = shiftnum;
        this.description = description;
        this.startday = startday;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getShiftnum() {
        return this.shiftnum;
    }
    
    public void setShiftnum(String shiftnum) {
        this.shiftnum = shiftnum;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getStartday() {
        return this.startday;
    }
    
    public void setStartday(String startday) {
        this.startday = startday;
    }
   


    public Long getDaymold() {
		return daymold;
	}

	public void setDaymold(Long daymold) {
		this.daymold = daymold;
	}





}