package combiz.domain.cal;

import java.util.Date;


/**
 * Calshiftday generated by MyEclipse - Hibernate Tools
 */

public class Calshiftday  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String shiftnum;
     private Long dayseq;
     private String starttime;
     private String endtime;
     private Float workhours;
     private String workday;


    // Constructors


	/** default constructor */
    public Calshiftday() {
    }

	/** minimal constructor */
    public Calshiftday(String shiftnum, Long dayseq) {
        this.shiftnum = shiftnum;
        this.dayseq = dayseq;
    }
    
    /** full constructor */
    public Calshiftday(String shiftnum, Long dayseq, String starttime, String endtime, Float workhours) {
        this.shiftnum = shiftnum;
        this.dayseq = dayseq;
        this.starttime = starttime;
        this.endtime = endtime;
        this.workhours = workhours;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getShiftnum() {
        return this.shiftnum;
    }
    
    public void setShiftnum(String shiftnum) {
        this.shiftnum = shiftnum;
    }

    public Long getDayseq() {
        return this.dayseq;
    }
    
    public void setDayseq(Long dayseq) {
        this.dayseq = dayseq;
    }

    public String getStarttime() {
        return this.starttime;
    }
    
    public void setStarttime(String starttime) {
        this.starttime = starttime;
    }

    public String getEndtime() {
        return this.endtime;
    }
    
    public void setEndtime(String endtime) {
        this.endtime = endtime;
    }

    public Float getWorkhours() {
        return this.workhours;
    }
    
    public void setWorkhours(Float workhours) {
        this.workhours = workhours;
    }
   

    public String getWorkday() {
		return workday;
	}

	public void setWorkday(String workday) {
		this.workday = workday;
	}







}