package combiz.domain.location;



/**
 * Locance generated by MyEclipse - Hibernate Tools
 */

public class Locance  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String location;
     private String ancestor;
     private String systemid;


    // Constructors

    /** default constructor */
    public Locance() {
    }

    
    /** full constructor */
    public Locance(String location, String ancestor, String systemid) {
        this.location = location;
        this.ancestor = ancestor;
        this.systemid = systemid;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    public String getAncestor() {
        return this.ancestor;
    }
    
    public void setAncestor(String ancestor) {
        this.ancestor = ancestor;
    }

    public String getSystemid() {
        return this.systemid;
    }
    
    public void setSystemid(String systemid) {
        this.systemid = systemid;
    }
   








}