package combiz.domain.location;



/**
 * Lochiery generated by MyEclipse - Hibernate Tools
 */

public class Lochiery  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String location;
     private String parent;
     private String systemid;
     private Long loclevel;
     private String leveltext;
     private String haschild;


    // Constructors

    /** default constructor */
    public Lochiery() {
    }

	/** minimal constructor */
    public Lochiery(String location, String systemid, Long loclevel, String haschild) {
        this.location = location;
        this.systemid = systemid;
        this.loclevel = loclevel;
        this.haschild = haschild;
    }
    
    /** full constructor */
    public Lochiery(String location, String parent, String systemid, Long loclevel, String leveltext, String haschild) {
        this.location = location;
        this.parent = parent;
        this.systemid = systemid;
        this.loclevel = loclevel;
        this.leveltext = leveltext;
        this.haschild = haschild;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    public String getParent() {
        return this.parent;
    }
    
    public void setParent(String parent) {
        this.parent = parent;
    }

    public String getSystemid() {
        return this.systemid;
    }
    
    public void setSystemid(String systemid) {
        this.systemid = systemid;
    }

    public Long getLoclevel() {
        return this.loclevel;
    }
    
    public void setLoclevel(Long loclevel) {
        this.loclevel = loclevel;
    }

    public String getLeveltext() {
        return this.leveltext;
    }
    
    public void setLeveltext(String leveltext) {
        this.leveltext = leveltext;
    }

    public String getHaschild() {
        return this.haschild;
    }
    
    public void setHaschild(String haschild) {
        this.haschild = haschild;
    }
   








}