package combiz.domain.location;



/**
 * Locsystem generated by MyEclipse - Hibernate Tools
 */

public class Locsystem  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String systemid;
     private String description;
     private String isdefault;

    // Constructors

    /** default constructor */
    public Locsystem() {
    }

	/** minimal constructor */
    public Locsystem(String systemid) {
        this.systemid = systemid;
    }
    
    /** full constructor */
    public Locsystem(String systemid, String description) {
        this.systemid = systemid;
        this.description = description;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getSystemid() {
        return this.systemid;
    }
    
    public void setSystemid(String systemid) {
        this.systemid = systemid;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

	public String getIsdefault() {
		return isdefault;
	}

	public void setIsdefault(String isdefault) {
		this.isdefault = isdefault;
	}
   








}