package combiz.domain.location;

import java.util.Date;


/**
 * Locstatus generated by MyEclipse - Hibernate Tools
 */

public class Locstatus  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String location;
     private String status;
     private Date statusdate;
     private String changeby;
     private Date changedate;
     private String memo;


    // Constructors

    /** default constructor */
    public Locstatus() {
    }

	/** minimal constructor */
    public Locstatus(String location, String status, Date statusdate, String changeby, Date changedate) {
        this.location = location;
        this.status = status;
        this.statusdate = statusdate;
        this.changeby = changeby;
        this.changedate = changedate;
    }
    
    /** full constructor */
    public Locstatus(String location, String status, Date statusdate, String changeby, Date changedate, String memo) {
        this.location = location;
        this.status = status;
        this.statusdate = statusdate;
        this.changeby = changeby;
        this.changedate = changedate;
        this.memo = memo;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public Date getStatusdate() {
        return this.statusdate;
    }
    
    public void setStatusdate(Date statusdate) {
        this.statusdate = statusdate;
    }

    public String getChangeby() {
        return this.changeby;
    }
    
    public void setChangeby(String changeby) {
        this.changeby = changeby;
    }

    public Date getChangedate() {
        return this.changedate;
    }
    
    public void setChangedate(Date changedate) {
        this.changedate = changedate;
    }

    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }
   








}