package combiz.domain.kpi;



/**
 * Kpitarget generated by MyEclipse - Hibernate Tools
 */

public class Kpitarget  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String kpinum;
     private String kpisql;
     private String description;
     private String kpitype;

    // Constructors

    public String getKpitype() {
		return kpitype;
	}


	public void setKpitype(String kpitype) {
		this.kpitype = kpitype;
	}


	public String getDescription() {
		return description;
	}


	public void setDescription(String description) {
		this.description = description;
	}


	/** default constructor */
    public Kpitarget() {
    }

    
    /** full constructor */
    public Kpitarget(String kpinum, String kpisql) {
        this.kpinum = kpinum;
        this.kpisql = kpisql;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getKpinum() {
        return this.kpinum;
    }
    
    public void setKpinum(String kpinum) {
        this.kpinum = kpinum;
    }

    public String getKpisql() {
        return this.kpisql;
    }
    
    public void setKpisql(String kpisql) {
        this.kpisql = kpisql;
    }
   








}