package combiz.domain.finance;



/**
 * Currency generated by MyEclipse - Hibernate Tools
 */

public class Currency  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String currency;
     private String description;
     private String active;


    // Constructors

    /** default constructor */
    public Currency() {
    }

	/** minimal constructor */
    public Currency(String currency, String active) {
        this.currency = currency;
        this.active = active;
    }
    
    /** full constructor */
    public Currency(String currency, String description, String active) {
        this.currency = currency;
        this.description = description;
        this.active = active;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getActive() {
        return this.active;
    }
    
    public void setActive(String active) {
        this.active = active;
    }
   








}