package combiz.domain.company;



/**
 * Compcontact generated by MyEclipse - Hibernate Tools
 */

public class Compcontact  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String company;
     private String contact;
     private String position;
     private String faxphone;
     private String email;
     private String homephone;
     private String officephone;
     private String mobilephone;


    // Constructors

    /** default constructor */
    public Compcontact() {
    }

	/** minimal constructor */
    public Compcontact(String company, String contact) {
        this.company = company;
        this.contact = contact;
    }
    
    /** full constructor */
    public Compcontact(String company, String contact, String position, String faxphone, String email, String homephone, String officephone, String mobilephone) {
        this.company = company;
        this.contact = contact;
        this.position = position;
        this.faxphone = faxphone;
        this.email = email;
        this.homephone = homephone;
        this.officephone = officephone;
        this.mobilephone = mobilephone;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }

    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }

    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }

    public String getFaxphone() {
        return this.faxphone;
    }
    
    public void setFaxphone(String faxphone) {
        this.faxphone = faxphone;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getHomephone() {
        return this.homephone;
    }
    
    public void setHomephone(String homephone) {
        this.homephone = homephone;
    }

    public String getOfficephone() {
        return this.officephone;
    }
    
    public void setOfficephone(String officephone) {
        this.officephone = officephone;
    }

    public String getMobilephone() {
        return this.mobilephone;
    }
    
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone;
    }
   








}