package combiz.domain.smsg;

import java.util.Date;


/**
 * Msgreceive generated by MyEclipse - Hibernate Tools
 */

public class Msgreceive  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String title;
     private String body;
     private Date sddate;
     private String sendtype;
     private String sender;
     private String rectype;
     private String receiver;
     private String hasread;


    // Constructors

    /** default constructor */
    public Msgreceive() {
    }

	/** minimal constructor */
    public Msgreceive(String title, Date sddate, String sendtype, String sender, String rectype, String receiver, String hasread) {
        this.title = title;
        this.sddate = sddate;
        this.sendtype = sendtype;
        this.sender = sender;
        this.rectype = rectype;
        this.receiver = receiver;
        this.hasread = hasread;
    }
    
    /** full constructor */
    public Msgreceive(String title, String body, Date sddate, String sendtype, String sender, String rectype, String receiver, String hasread) {
        this.title = title;
        this.body = body;
        this.sddate = sddate;
        this.sendtype = sendtype;
        this.sender = sender;
        this.rectype = rectype;
        this.receiver = receiver;
        this.hasread = hasread;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }

    public Date getSddate() {
        return this.sddate;
    }
    
    public void setSddate(Date sddate) {
        this.sddate = sddate;
    }

    public String getSendtype() {
        return this.sendtype;
    }
    
    public void setSendtype(String sendtype) {
        this.sendtype = sendtype;
    }

    public String getSender() {
        return this.sender;
    }
    
    public void setSender(String sender) {
        this.sender = sender;
    }

    public String getRectype() {
        return this.rectype;
    }
    
    public void setRectype(String rectype) {
        this.rectype = rectype;
    }

    public String getReceiver() {
        return this.receiver;
    }
    
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    public String getHasread() {
        return this.hasread;
    }
    
    public void setHasread(String hasread) {
        this.hasread = hasread;
    }
   








}