package combiz.domain.smsg;



/**
 * Phrase generated by MyEclipse - Hibernate Tools
 */

public class Phrase  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String type;
     private String description;
     private String ownertable;
     private String phrasenum;

    // Constructors

    /** default constructor */
    public Phrase() {
    }

	/** minimal constructor */
    public Phrase(String description) {
        this.description = description;
    }
    
    /** full constructor */
    public Phrase(String type, String description, String ownertable) {
        this.type = type;
        this.description = description;
        this.ownertable = ownertable;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getOwnertable() {
        return this.ownertable;
    }
    
    public void setOwnertable(String ownertable) {
        this.ownertable = ownertable;
    }

	public String getPhrasenum() {
		return phrasenum;
	}

	public void setPhrasenum(String phrasenum) {
		this.phrasenum = phrasenum;
	}
   








}